#!/bin/bash

# Copyright © 2009-2016 Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>

# Created one day in 2009
# Last changed: 2016-02-25 14:21:37

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.

# check arguments
if test $# -ne 2; then
    echo "Usage: $0 config_file user"
    exit 1
fi

# source configuration
. $1
shift

# check user existance
user=$1
id $user > /dev/null 2>&1
if test $? -ne 0; then
    echo "user $user not found"
    exit 1
fi

# find user details
u_id=$(id -u ${user})
g_id=$(id -g ${user})
jail=$(sed -n "s/^${user}:[^:]\+:[^:]\+:[^:]\+:[^:]\+:\([^:]\+\):.\+\$/\1/p" \
    < /etc/passwd)
shell=$(sed -n "s/^${user}:.*:\([^:]\+\)\$/\1/p" < /etc/passwd)

COMMANDS="${COMMANDS} ${shell}"

# make sure jail directory is not too dangerous
if test -z "${jail}" -o "${jail}" == "/"; then
    echo "Error not a valid jail directory: ${jail}"
    exit 1
fi

# create home directory if necessary in real FS and inside the jail
for d in "${jail}" "${jail}/${jail}"; do
    if ! test -d "${d}"; then
	mkdir -p "${d}"
	chown ${u_id}.${g_id} "${d}"
    fi
done

# home in real FS has to me owned by root
chown root.root "${jail}"

echo "Purging old jail in ${jail}"
find ${jail}/{bin,etc,dev,lib,usr}  -type f -or -type d -print0 | xargs -0 chattr -V -i
rm -fvr ${jail}/{bin,etc,dev,lib,usr}

echo "copying requiered commands and files"
tar -cf - ${COMMANDS} | tar -C "${jail}" -xvf - | sed 's/^/\t/'

if ! test -z "${EXTRA}"; then
    echo "copying extra files files"
    tar -chf - ${EXTRA} | tar -C "${jail}" -xvf - | sed 's/^/\t/'
fi

echo "copying required libs"
echo ${COMMANDS} | xargs ldd | tr -s ' ' | \
    sed -n 's,.*[[:space:]]\(/.*\)[[:space:]]\+(.*,\1,p' | \
    sort | uniq | \
    tar -ch -f - -T - | tar -C "${jail}" -xvf - | sed 's/^/\t/'

echo "copying required devices"
echo ${COMMANDS} | xargs strings | grep '^/dev/.\+' | sort -u | \
    grep -v '^/dev/fd/$' | \
    tar -ch -f - -T -  | tar -C "${jail}" -xvf - | sed 's/^/\t/'

echo "copying extra files"
for dir in ${EXTRA_FILES_DIRS}; do
    tar -C "$dir" -cf - . | tar -C "${jail}" -xvf - | sed 's/^/\t/'
done

echo "copying NSS info"
mkdir -p "${jail}/etc"
tar -cf - /lib/**/libnss_compat* /lib/**/libnss_files* | \
    tar -C "${jail}" -xvf - |sed 's/^/\t/'

echo "Adding password entries"
grep "^root:\|^${user}:" /etc/passwd | \
    awk -F: '{print $1 ":" $2 ":" $3 ":" $4 ":" $1 ":/:/dev/null" }' \
    > "${jail}/etc/passwd"
grep "^root:\|^${user}:" /etc/passwd | \
    awk -F: '{print $1 ":" $2 ":" $4 ":"}' > "${jail}/etc/group"

echo "Create default shell for user."
ln -nfs ${shell} "${jail}/bin/sh"

echo "Forbid system jail file modification"
find ${jail}/{bin,etc,dev,lib,usr}  -type f -or -type d -print0  | xargs -0 chattr -V +i
